apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rjshrjndrn/argocd-example-apps.git
    targetRevision: dev
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
